create table public.mesas (
  id bigint generated by default as identity not null,
  numero smallint not null,
  tipo text null,
  imagen text null,
  qr text null,
  comensales smallint null,
  ocupada boolean null default false,
  "clienteAsignadoId" bigint null,
  pedido_id bigint null,
  constraint mesas_pkey primary key (id),
  constraint mesas_clienteAsignadoId_fkey foreign KEY ("clienteAsignadoId") references clientes (id),
  constraint mesas_pedido_id_fkey foreign KEY (pedido_id) references pedidos (id)
) TABLESPACE pg_default;
INSERT INTO "public"."mesas" ("id", "numero", "tipo", "imagen", "qr", "comensales", "ocupada", "clienteAsignadoId", "pedido_id") VALUES ('1', '3', 'estandar', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-3-pollo-frito.png', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-3-qr.png', '4', 'false', null, null), ('2', '2', 'vip', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-2-mesita.jpg', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-2-qr.png', '6', 'false', null, null), ('3', '5', 'estandar', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-5-mesita.jpg', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-5-qr.png', '2', 'true', '41', '38'), ('4', '12', 'discapacitados', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-12-mesa12.jpg', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-12-qr.png', '6', 'false', '5', null), ('5', '7', 'vip', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-7-mesa12.jpg', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-7-qr.png', '8', 'false', null, null), ('6', '9', 'vip', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-9-JPEG_20251003_212145_7800586794882004786.jpg', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-9-qr.png', '5', 'false', '7', null), ('7', '6', 'vip', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/imagenes/mesa-6-vilma%20palma%20e%20vampiros.jpeg', 'https://jpwlvaprtxszeimmimlq.supabase.co/storage/v1/object/public/qrs/mesa-6-qr.png', '2', 'true', '9', null);