services:
  - type: web
    name: los-fritos-hermanos-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: FIREBASE_ADMIN_CREDENTIALS
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true
